apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmruvenweb.fullname" . }}
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  labels:
    {{- include "helmruvenweb.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: "Local"
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmruvenweb.selectorLabels" . | nindent 4 }}
